service: express-graphql

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 1024
  timeout: 20
  stage: dev

functions:
  graphql-api-func:
    handler: build/index.handler
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY
    environment:
      DATABASE_URL: ${env:DATABASE_URL}


package:
  patterns:
    - 'prisma/**'
    - 'build/**'
    - 'node_modules/**'
    - 'package.json'
    - '!src/**'
    - '!.github'
    - '!tsconfig.json'
    - '!package-lock.json'
